### ISSUE TITLE
Pure JS image manipulation

### ISSUE THREAD

**Issue by aldeed** [meteorhybrid/assets#1]
Seems like a good start!

Did you consider avoiding the graphicsmagick hassle by using something like [jimp](https://www.npmjs.com/package/jimp) or [camanjs](http://camanjs.com/)? If it's just resize and crop, I think it should be possible.

**Comment by andrewreedy** [comment]
I'm also doing quality and some other methods in the next version. Once I get it to a good place I'll take a look at a speed comparison and test vs `jimp` since it looks like they copied the API it will be easy to do some tests.

**Comment by andrewreedy** [comment]
I'm also using `GraphicMagick's compare() function to avoid recreating images in the next version so this might make using `jimp` a little less possible too. We will see though :)

**Comment by andrewreedy** [comment]
I'm closing this issue since `jimp` doesn't have a compare function and `gm` is more feature rich.
